### ISSUE TITLE
[Feature Request] folder color variants

### ISSUE THREAD

**Issue by ceyhunnabiyev** [vinceliuice/Tela-icon-theme#1]
First of all, thank you for the nice icons. It would be nice to add place color variants.

**Comment by vinceliuice** [comment]
No problem! I'll add at future update

**Comment by vinceliuice** [comment]
Now colorful folder variants are already finished, try the last update

**Comment by ceyhunnabiyev** [comment]
Would you mind to add Manjaro specific color folder?

**Comment by vinceliuice** [comment]
No problem!
