### ISSUE TITLE
[Icon Request] Rimworld

### ISSUE THREAD

**Issue by Dohvakin** [vinceliuice/Tela-icon-theme#101]
Please make the icon for

https://store.steampowered.com/app/294100/RimWorld/

![1571593669_preview_972404022_preview_1472488430_rimworld](https://user-images.githubusercontent.com/26587446/90895949-7b5b9380-e3e0-11ea-832e-de8393454714.png)

**Comment by Wisdawn** [comment]
This page is currently a top Google Images search result. So, here are slightly better versions of this for Linux and other users who may need RimWorld's app icon with transparency.

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/059f8b54-78ed-4f3a-a614-d4e375d36733" />
<img width="320" height="320" alt="Image" src="https://github.com/user-attachments/assets/68f8d9ff-4d41-4c06-b2d3-d64508b3de34" />
