### ISSUE TITLE
Xfce logoff hibernate icon

### ISSUE THREAD

**Issue by michelfritsch** [vinceliuice/Tela-icon-theme#119]
Wrong hibernate icon on xfce logoff (xfce 4.12)

![logoff_xfce_4 12](https://user-images.githubusercontent.com/26671487/97468080-a48a2a00-1923-11eb-82af-28c8d87c6020.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed

**Comment by michelfritsch** [comment]
Thanks
