### ISSUE TITLE
[Icon request] SmartGit

### ISSUE THREAD

**Issue by ayanb1991** [vinceliuice/Tela-icon-theme#12]
- **App Name:** SmartGit
- **Icon Name:** smartgit
- **Description:** A visual git repo management tool
- **Webpage (optional):** https://www.syntevo.com/smartgit/
- **Original Icon:**
   ![smartgit-256](https://user-images.githubusercontent.com/14938120/56547250-77282780-659a-11e9-9e79-cee4847f9a64.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
It's add now
