### ISSUE TITLE
[Icon Request] Pgadmin4

### ISSUE THREAD

**Issue by pedro-augusto-santana** [vinceliuice/Tela-icon-theme#121]
App Name: pgAdmin4
Description: A PostgreSQL manager / administration platform
Website: https://www.pgadmin.org/
Icon:
![image](https://user-images.githubusercontent.com/48259258/98703700-87f5e500-235a-11eb-8f1c-c3894dda8765.png)

**Comment by paulocoghi** [comment]
I'm trying to get the SVG from this one:

![postgresql](https://user-images.githubusercontent.com/378397/98717277-9d273f80-236b-11eb-94f0-67267d62a591.jpg)
