### ISSUE TITLE
[Icon Request] VirtualBox VM

### ISSUE THREAD

**Issue by arthurflor23** [vinceliuice/Tela-icon-theme#123]
Hello,

When starting a virtual machine in the VirtualBox, the new instance icon is missing:

![image](https://user-images.githubusercontent.com/11759042/99689877-4229d280-2a66-11eb-9829-7bfaee03b346.png)

Look for solved this problem, I found this:

```
Create ~/.local/share/applications/virtualbox-machine.desktop file with the following content to fix that:

[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Virtual Machine
GenericName=Virtual Machine
Type=Application
Icon=virtualbox
Categories=Emulator;System;
Actions=Manager;
StartupWMClass=VirtualBox Machine
Comment=Run several virtual systems on a single host computer
NoDisplay=true
```

However, the icon is the same as the VirtualBox application:

![image](https://user-images.githubusercontent.com/11759042/99689798-2e7e6c00-2a66-11eb-8bfa-da28dee20851.png)

Would it be interesting to create an icon for VMs? Indicating that it is a VM in fact

**Comment by OckhamOdyssey** [comment]
I would like to have .ova and .vdi mimetypes
