### ISSUE TITLE
Wrong icon size with 4K screen, 300% scaling

### ISSUE THREAD

**Issue by shmgqn** [vinceliuice/Tela-icon-theme#127]
Ubuntu 20.04.1, screen resolution 3840x2160
All icons have the same size under 200% scaling:
![Screenshot from 2020-12-08 19-16-05](https://user-images.githubusercontent.com/49809823/101477706-8e43a500-398a-11eb-8ed8-d38761eaa743.png)
Shutdown icon and wired connection icon is abnormal under 300% scaling:
![Screenshot from 2020-12-08 19-16-31](https://user-images.githubusercontent.com/49809823/101478119-22ae0780-398b-11eb-9d20-bdc7ff5a0fbc.png)
Official icon theme of Ubuntu "Yaru" does not have such a problem.

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed
