### ISSUE TITLE
VSCodium

### ISSUE THREAD

**Issue by Tsumuri-u** [vinceliuice/Tela-icon-theme#129]
**Tell me things about the app or icon**
1. App name: VSCodium
2. App Website: https://github.com/VSCodium/vscodium
3. App icon name: vscodium

The current VSCodium icon in the pack uses the old logo
![code](https://user-images.githubusercontent.com/68445671/102717882-e7201100-4299-11eb-90b8-172097cff2cb.png)

But there is a new logo inspired by the Visual Studio design. It would be nice if the icon pack also adopted this new logo.
![Screenshot from 2020-12-20 08-03-21](https://user-images.githubusercontent.com/68445671/102717904-0880fd00-429a-11eb-93d9-f80270174ca6.png)

**Comment by vinceliuice** [comment]
I'll update this
