### ISSUE TITLE
make battery low icon red

### ISSUE THREAD

**Issue by peterwu** [vinceliuice/Tela-icon-theme#131]
**Describe the bug**
When battery is low, the icon should change to red.

**To Reproduce**
1. Let the system go low on battery, ideally below 10%
2. Observe the battery icon on the top right corner

**Expected behavior**
The icon should turn red

**Screenshots**
![low-battery-icon-not-red](https://user-images.githubusercontent.com/584751/103177353-ad29ae80-4847-11eb-9871-da46efb87f17.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33
- Gnome 3.38

**Comment by vinceliuice** [comment]
I'll fix this!
