### ISSUE TITLE
[Icon request] [GoLand]

### ISSUE THREAD

**Issue by kareemkasem** [vinceliuice/Tela-icon-theme#133]
**App name**: GoLand
**App Webside**: [goland](https://www.jetbrains.com/go/)
**App icon name**: goland or com.jetbrains.GoLand or jetbrains-goland

**Comment by vinceliuice** [comment]
You need to edit the Desktop Entry (starter) file, modify the line: `icon= ~~`
Jetbrains apps don't use user theme icon

**Comment by songhd** [comment]
![image](https://user-images.githubusercontent.com/6183393/105193561-95f28e00-5b73-11eb-9999-09542f4f2488.png)
![image](https://user-images.githubusercontent.com/6183393/105193648-ab67b800-5b73-11eb-8208-a411d89b3252.png)
Still missing golang or Jetbrains-goland etc. Could you please add it.

**Comment by vinceliuice** [comment]
No problem!

**Comment by songhd** [comment]
老哥你理解错了，是缺少 goland.svg 图标这个原文件，我看昨天你加了两个软链。

**Comment by vinceliuice** [comment]
这不是吗src/scalable/apps/golang.svg加了呀

**Comment by songhd** [comment]
看到了谢谢，github这个go to file功能搜不到这个文件，我以为没加，抱歉
