### ISSUE TITLE
What is the difference between Tela icon and Tela circle

### ISSUE THREAD

**Issue by AnwarShah** [vinceliuice/Tela-icon-theme#135]
There was a difference once. But now, I don't see any difference with latest updates. What are those?

**Comment by vinceliuice** [comment]
Difference between Tela icon and Tela circle? only app icons are different

**Comment by AnwarShah** [comment]
Can you be specific on which apps? I tried to check the difference but looks both same.

**Comment by vinceliuice** [comment]
this is tela:
![Tela](https://github.com/vinceliuice/Tela-icon-theme/raw/master/tela-dark.png)
and this tela-circle:
![Tela-circle](https://github.com/vinceliuice/Tela-circle-icon-theme/raw/master/preview.png)

**Comment by vinceliuice** [comment]
Tela circle all app icons are circular

**Comment by vinceliuice** [comment]
Did you download the tela circle from the right place: https://github.com/vinceliuice/Tela-circle-icon-theme

**Comment by AnwarShah** [comment]
@vinceliuice Ok, got it. Yes I downloaded from the right place
