### ISSUE TITLE
Missing icons on gkt applications

### ISSUE THREAD

**Issue by c30ra** [vinceliuice/Tela-icon-theme#138]
Missing icons on gtk applications

**To Reproduce**
open any gtk application under kubuntu

**Expected behavior**.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Kubuntu]
 - App [e.g. any gkt application, tested on grub-customizer, gparted]

**Additional context**

**Comment by vinceliuice** [comment]
What's your kubuntu version? old kde version the kde and gtk icons are set separately

**Comment by c30ra** [comment]
is the last one: 20.10

**Comment by vinceliuice** [comment]
Could you show me some screenshot?

**Comment by c30ra** [comment]
![immagine](https://user-images.githubusercontent.com/16150836/105626111-1cd28f80-5e2e-11eb-9430-8e73b264d0fe.png)
![immagine](https://user-images.githubusercontent.com/16150836/105626123-3b388b00-5e2e-11eb-976a-a05efc969fe3.png)
![immagine](https://user-images.githubusercontent.com/16150836/105626139-51dee200-5e2e-11eb-9f67-ffc504e1879f.png)

**Comment by vinceliuice** [comment]
Did you install this theme with sudo? Gparted can only use on root user

**Comment by vinceliuice** [comment]
I think you need reinstall them

**Comment by c30ra** [comment]
> Did you install this theme with sudo? Gparted can only use on root user

I've installed it with plasma theme installer, and no sudo was asked. To install it with sudo I've to install them manually. I'll try to do it in these days

**Comment by vinceliuice** [comment]
You can download from github and try with sudo again

**Comment by c30ra** [comment]
tried, doesn't work... on console it even say that GTK icon cache was updated

**Comment by vinceliuice** [comment]
![2021-01-25 23-52-10 的屏幕截图](https://user-images.githubusercontent.com/7604295/105729638-6921ea80-5f68-11eb-8b52-a5787690b1f9.png)
I don't know what's going on, but everything works fine on my desktop

**Comment by c30ra** [comment]
Just for info I've tried other icons pack and all have the same problem. Only the default shipped with kubuntu work...
It's just a fresh installation, so I didn't even mess up with config files..

**Comment by c30ra** [comment]
Found the problem, basically the default adawita icons were not installed properly. As I understand themes falls back on other themes, and since adawita were not installed correctly the icon were missing.

I've just used this `sudo apt-get install --reinstall adwaita-icon-theme-full` and fixed every thing

[source](https://ubuntuforums.org/showthread.php?t=2392578)
