### ISSUE TITLE
TeXWorks (and tex editors in general) icon request

### ISSUE THREAD

**Issue by macco3k** [vinceliuice/Tela-icon-theme#14]
Is there any chance you could add icons for TexWorks and TeX-related editors? One icon for all of theme would be nice I suppose.

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added now

**Comment by macco3k** [comment]
Super cool, but you might want to add TeXworks.svg as well as a symbolic link, as that's missing ;)

**Comment by vinceliuice** [comment]
No problem
