### ISSUE TITLE
[Icon request] Chrome Shortcuts 

### ISSUE THREAD

**Issue by edraft** [vinceliuice/Tela-icon-theme#140]
App name: Chrome Shortcuts
App Webside: https://support.google.com/chrome_webstore/answer/3060053?hl=de

Context:
On the Ubuntu 2020.04 desktop, the Chrome icon is displayed for the Chrome shortcuts.
It would be better if the shortcut icon is shown.
E.g. YoutTube Music:

What it looks like:
![2021-02-28_15-38](https://user-images.githubusercontent.com/44439074/109422258-18743600-79db-11eb-873b-41b3cbb15d11.png)

What it should show:
![chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default](https://user-images.githubusercontent.com/44439074/109422298-42c5f380-79db-11eb-9583-87acd43cb4b1.png)

Shortcut code:
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=YouTube Music
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod
Icon=chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default
StartupWMClass=crx_cinhimbnkkaeohfgghhklpknlkffjgod

**Comment by edraft** [comment]
It works with WhatsApp:
![2021-02-28_15-44](https://user-images.githubusercontent.com/44439074/109422464-e7e0cc00-79db-11eb-8820-65e8d85ff190.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by edraft** [comment]
Well you fixed it for YT music but not for PWAs in general....
