### ISSUE TITLE
[Icon Request] [Krita]

### ISSUE THREAD

**Issue by pedro-augusto-santana** [vinceliuice/Tela-icon-theme#154]
1. App name: Krita
2. App Website: https://krita.org/en
3. App icon name: krita

Original icon url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F73%2FCalligrakrita-base.svg%2F1200px-Calligrakrita-base.svg.png&f=1&nofb=1

**Comment by vinceliuice** [comment]
Added
