### ISSUE TITLE
[Icon Request] Cryptomator

### ISSUE THREAD

**Issue by buchwasa** [vinceliuice/Tela-icon-theme#157]
**Tell me things about the app or icon**
1. App name: Cryptomator
2. App Website:  https://cryptomator.org
3. App icon name: org.cryptomator.Cryptomator

**Additional context**
<img src="https://user-images.githubusercontent.com/17461354/123363034-b8803d00-d53f-11eb-8ba9-d49d50862bac.png" width="25%" height="25%">

**Comment by vinceliuice** [comment]
Added
