### ISSUE TITLE
[Icon Request] Yubico Authenticator

### ISSUE THREAD

**Issue by buchwasa** [vinceliuice/Tela-icon-theme#158]
**Tell me things about the app or icon**
1. App name: Yubico Authenticator
2. App Website: https://developers.yubico.com/yubioath-desktop/
3. App icon name: com.yubico.yubioath

**Additional context**
<img src="https://user-images.githubusercontent.com/17461354/123363340-42300a80-d540-11eb-9abf-5afd4ce8d2d0.png"  width="25%" height="25%">

**Comment by vinceliuice** [comment]
Added
