### ISSUE TITLE
distributor-logo is incorrect in Pop_OS!

### ISSUE THREAD

**Issue by nor2101** [vinceliuice/Tela-icon-theme#165]
**Describe the bug**
The system logo / distributor logo icon in Pop_OS! is replaced by Ubuntu's.

**To Reproduce**
1. Go to 'Settings'
2. Scroll down to 'Informations' and click on it
3. See error

**Expected behavior**
The 'distributor-logo-pop-os.svg' icon should appear instead of 'distributor-logo-ubuntu.svg'.

**Desktop (please complete the following information):**
 - OS: [Pop_OS!]
 - Version [21.04]

**Comment by vinceliuice** [comment]
Added
