### ISSUE TITLE
Icon Request: Zorin OS

### ISSUE THREAD

**Issue by mareasperez** [vinceliuice/Tela-icon-theme#166]
1. App name: (Zorin OS)
2. App Webside: [https://zorin.com/os/](https://zorin.com/os/)
3. App icon name: (Zorin OS)

**Additional context**
The grub's themes are very beautiful i love its but the in my  Zorin's grub entry the icon is the default linux icon:

![linux](https://user-images.githubusercontent.com/28939539/133531220-b875a33e-11ac-416a-b4f1-009d2ba68580.png)![gnu-linux](https://user-images.githubusercontent.com/28939539/133531216-2942ca52-11b2-4787-9c99-bc738870132e.png)![lfs](https://user-images.githubusercontent.com/28939539/133531218-065296c3-173d-4f01-af09-e773ae70cef5.png)
Instead of the zorin os logo:
![zorin](https://user-images.githubusercontent.com/28939539/133531429-059b2874-33c2-4342-93c8-da6ae84c986d.png)![zorinos](https://user-images.githubusercontent.com/28939539/133531433-8c58df0c-304a-4612-afc8-2da333cd978e.png)
All users of this beautiful theme pack and this operating system would be very grateful if you add the corresponding icon for zorin os

**Comment by vinceliuice** [comment]
Fixed on grub theme
