### ISSUE TITLE
XFCE - Icons don't get resized properly (again) after 4.16 update

### ISSUE THREAD

**Issue by 22cms** [vinceliuice/Tela-icon-theme#173]
**Describe the bug**
Basically the same problem that I described [here](https://github.com/vinceliuice/Tela-icon-theme/issues/169), but now happening on a newer version of XFCE (4.16) and on different icons. Now it happens on the Desktop Icon and on the Battery Icon:
![Issue](https://i.imgur.com/QNjsUh9.png)

**To Reproduce**
1. Install the icon pack via install.sh
2. Open the "Appearance" XFCE App
3. Set Tela-dark in this case as the Icon pack in use
4. Right click on XFCE's Panel, go to Panel > Panel's Preferences
5. Go to Elements and add PulseAudio and XFCE Energy Management's Applets
6. Look at your right-down corner (or wherever your Panel and indicators are placed)

**Expected behavior**
Icons should resize themself to around 16px

**Screenshots**
Already provided on top/down

**Desktop (please complete the following information):**
 - OS: MX Linux 21, based on Debian Bullseye (11) Stable
 - App XFCE
 - Version 4.16

**Additional context**
I actually tried to figure out why this now happened again with just an update, so I ran xfce4-panel with GTK Interactive Debugging on, and I actually managed to fix the Desktop icon by making a symlink from user-desktop.svg to org.xfce.panel.showdesktop.svg, apparently those icon names got changed on the new release.
I didn't manage to find a similar solution for the battery icon, but if I resize it manually (changing the pixel-size property) to 16px with the Debugger UI, the icon actually gets replaced with the 16px one (you can notice it 'cause the round angles become sharp):
![Tried to solve but I couldn't](https://i.imgur.com/ErZkvua.png)

**Comment by 22cms** [comment]
Update: I actually Managed to "fix" the battery icon issues too by just taking the battery icons from 16/panel and placing them in symbolic/status:
![The "fix"](https://i.imgur.com/sB92Ofu.png)
But I don't feel like this is the best solution though, could cause resizing issues on other DEs/applications, but it just works enough for XFCE at the moment.

**Comment by vinceliuice** [comment]
I'll fix this!
