### ISSUE TITLE
Icons missing when installing from git with custom color

### ISSUE THREAD

**Issue by nclarius** [vinceliuice/Tela-icon-theme#174]
When I install the theme from git with a custom color, many icons are missing:

![Screenshot_2021-11-19_13-59-10](https://user-images.githubusercontent.com/13196860/142627405-01cac009-fd45-4198-b86c-202c69398c52.png)

When installing the icons from the store with the standard colors, everything is fine.

Operating System: Arch Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.2-arch1-1 (64-bit)

**Comment by vinceliuice** [comment]
What command you used?

**Comment by vinceliuice** [comment]
You did not install it success, try reinstall it and reboot your plasma

**Comment by nclarius** [comment]
I ran `.install.sh orange`.

Restarting didn't help.

**Comment by nclarius** [comment]
`rm ~/.cache/icon-cache.kcache` unfortunately did not help either.

**Comment by vinceliuice** [comment]
I don't know what happened when you install it, but everything works well on my desktop
![Screenshot_20211119_213702](https://user-images.githubusercontent.com/7604295/142631732-17cb6bcd-7295-423b-bede-0757bee2608f.png)

**Comment by vinceliuice** [comment]
Download this https://github.com/vinceliuice/Tela-icon-theme/archive/refs/tags/2021-11-05.tar.gz
and try again

**Comment by vinceliuice** [comment]
Maybe the zip file not works well on linux desktop

**Comment by vinceliuice** [comment]
After that reset your icon theme, and reopen your dolphin

**Comment by nclarius** [comment]
That worked. Thank you very much!

**Comment by vinceliuice** [comment]
You are welcome!
