### ISSUE TITLE
Nord icons for Tela?

### ISSUE THREAD

**Issue by scalarman** [vinceliuice/Tela-icon-theme#182]
Loving the Nord coloured options in the Graphite gtk theme, and was wondering if it would be possible to add Nord colours as options in the Tela icon theme.

**Comment by vinceliuice** [comment]
Added!

**Comment by scalarman** [comment]
Thanks!

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by ConstantMan** [comment]
I run ./install.sh nord but it says ERROR: Unrecognized installation option 'nord'
The other colors work just fine though
