### ISSUE TITLE
Some icon doesn't scale properly on large text

### ISSUE THREAD

**Issue by sh-himanshu** [vinceliuice/Tela-icon-theme#183]
**Describe the bug**

**To Reproduce**
1. In Gnome turn on 'accessibility > large text'
2. Goto 'Gnome panel'
3. Click on 'Battery and wifi icon'
4. See an error 'Display and power icon doesn't scale properly

**Expected behavior**
Proper scaling of icons

**Screenshots**

|                  Tela Icon                  |                  Tela Circle Icon              |
| :--------------------------------------------: | :------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/88159798/155854219-8c90c8a1-65e3-4feb-bcfd-3311704eab25.png) | ![image](https://user-images.githubusercontent.com/88159798/155854252-d2374b18-cd21-4512-94d2-e4c077f11b63.png) |

**Desktop (please complete the following information):**
 - OS: [Pop!_OS 21.10]
 - App [Gnome Panel] (Gnome 40)

**Additional context**
Some icons are not scaling well in Tela but are perfectly fine in Tela Circle Icons in large text.

**Comment by vinceliuice** [comment]
Fixed
