### ISSUE TITLE
The install script does not work like described.

### ISSUE THREAD

**Issue by stwnt** [vinceliuice/Tela-icon-theme#187]
```sh install.sh -n Tela-red``` nor ```sh install.sh -n red``` seem to work. I want to install (you guessed it) the red color scheme. It installs a folder called *Tela-red*, but in there is the default blue icons scheme. See #177 .

However if I use the ```-a``` option, it installs all color schemes including my desired red one.

**Desktop (please complete the following information):**
 - OS: Arch, Fedora 35
 - App Nautilus
 - Version 41, 42

**Comment by vinceliuice** [comment]
./install.sh red

**Comment by stwnt** [comment]
Maybe I'm the only one but i would update the ```--help``` and the ```README```, I understand that ```-n```  lets me choose a color, not a prefix for the folder it gets installed into.

**Comment by MolassesLover** [comment]
> Maybe I'm the only one but i would update the ```--help``` and the ```README```, I understand that ```-n```  lets me choose a color, not a prefix for the folder it gets installed into.

Yeah, I've been meaning to do this for a while. I'll get to it soon enough. Sorry for the inconvenience!
