### ISSUE TITLE
Manjaro logo inconsistency

### ISSUE THREAD

**Issue by MaycneSonahoz** [vinceliuice/Tela-icon-theme#188]
**Describe the bug**
There is an inconsistency in the Manjaro logo used for the icons: the distributor logo uses the old logo pattern, while the other            icons correctly use the newer one -- the left bar of the M now does not have a space in it:
- Distributor logo: https://github.com/vinceliuice/Tela-icon-theme/blob/master/src/scalable/apps/distributor-logo-manjaro.svg
- Manjaro Settings Manager icon: https://github.com/vinceliuice/Tela-icon-theme/blob/master/src/24/panel/manjaro-settings-manager-panel.svg
- Reference: https://manjaro.org/img/logo.svg

**Comment by MolassesLover** [comment]
Thank you for pointing this out! It's posts like these that help Tela Circle remain polished. I'll get to fixing it in a little bit
