### ISSUE TITLE
Calendar App in ElementaryOS shows Chinese.

### ISSUE THREAD

**Issue by cg-david** [vinceliuice/Tela-icon-theme#2]
Dear Vince, 

thanks for the incredible icon pack. Just saw it today and it becomes by far my absolute favorite! 
One thing though: I use  elementaryOS Juno and my Calendar app shows the month / weekday / whatever is on top in Chinese. Is there any way to change this into English? 

Thanks!

**Comment by Silicasandwhich** [comment]
I have this problem too but on manjaro gnome.

**Comment by fficusbenjamin** [comment]
Same problem on Pop_OS 19.04

**Comment by vinceliuice** [comment]
Can you show me a screenshot?

**Comment by fficusbenjamin** [comment]
![Screenshot from 2019-09-16 11-16-05](https://user-images.githubusercontent.com/43504188/64950663-d7827300-d873-11e9-950a-811684792d7f.png)

**Comment by vinceliuice** [comment]
It's just a icon style, not a bug
