### ISSUE TITLE
Some errors with simbolic links

### ISSUE THREAD

**Issue by beatussum** [vinceliuice/Tela-icon-theme#20]
Symbolic link _/usr/share/icons/Tela/24/panel/nm-device-wired-secureoffline.svg_ points to _/usr/share/icons/Tela/24/panel/network-vpn.svg_ which does not exist.
Symbolic link _/usr/share/icons/Tela/24/panel/nm-adhoc.svg_ points to _/usr/share/icons/Tela/24/panel/network-wireless-hotspot.svg_ which does not exist.
Symbolic link _/usr/share/icons/Tela/22/panel/nm-device-wired-secureoffline.svg_ points to _/usr/share/icons/Tela/22/panel/network-vpn.svg_ which does not exist.
Symbolic link _/usr/share/icons/Tela/22/panel/nm-adhoc.svg_ points to _/usr/share/icons/Tela/22/panel/network-wireless-hotspot.svg_ which does not exist.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by beatussum** [comment]
Thank for your answer!

**Comment by vinceliuice** [comment]
Fixed
