### ISSUE TITLE
[Icon request] Komikku

### ISSUE THREAD

**Issue by astro-ray** [vinceliuice/Tela-icon-theme#207]
**Tell me things about the app or icon**
1. App name: Komikku
2. App Website: or App Github Homepage: https://valos.gitlab.io/Komikku/
3. App icon name: info.febvre.Komikku

**Additional context**
It's a GTK4 manga reader app.

![info febvre Komikku](https://user-images.githubusercontent.com/69363775/208019270-37d2a638-8644-48fb-b7de-4e2a407b8eea.svg)

**Comment by vinceliuice** [comment]
Fixed
