### ISSUE TITLE
[Icon request] Rnote

### ISSUE THREAD

**Issue by astro-ray** [vinceliuice/Tela-icon-theme#208]
**Tell me things about the app or icon**
1. App name: Rnote
2. App Website: or App Github Homepage: https://github.com/flxzt/rnote
3. App icon name: com.github.flxzt.rnote

**Additional context**
A pretty awesome handwritten note-taking application. The best I have seen in Linux.

![rnote](https://user-images.githubusercontent.com/69363775/208020800-04757598-b238-45a4-8c5a-b8dd13e0f701.svg)

**Comment by vinceliuice** [comment]
Fixed
