### ISSUE TITLE
[Symbolic icon request] Elisa player

### ISSUE THREAD

**Issue by 64542426** [vinceliuice/Tela-icon-theme#209]
Request symbolic tray icon for music player [Elisa](https://invent.kde.org/multimedia/elisa) to fit other similar symbolic icons.

The first color icon is Elisa player.
![Screenshot_20221018_165739](https://user-images.githubusercontent.com/35492934/196468607-62e90e0d-cc79-4cd4-860a-f57233a4a839.png)

**Comment by vinceliuice** [comment]
Fixed
