### ISSUE TITLE
Colors are messed up on KDE

### ISSUE THREAD

**Issue by JanNowak94** [vinceliuice/Tela-icon-theme#210]
**Describe the bug**
follows KDE's colour

**To Reproduce**
1 set Tela-dark-{colour} as icon-set

**Expected behaviour**
follows {colour}
only Tela and Tela dark should follow KDE's colour

**Desktop (please complete the following information):**
 - OS: Arch
 - KDE 5.26

**Comment by vinceliuice** [comment]
Now It's fixed

**Comment by JanNowak94** [comment]
Still mismatch - for "grey" in install.sh
sed -i "/\ColorScheme-Background/s/currentColor/#ffffff" "${THEME_DIR}/scalable/places/"default-*.svg
should be rather
sed -i "/\ColorScheme-Background/s/currentColor/#666666/" "${THEME_DIR}/scalable/places/"default-*.svg
