### ISSUE TITLE
Some 16px folder icons won't receive color treatment

### ISSUE THREAD

**Issue by nptr** [vinceliuice/Tela-icon-theme#211]
**Describe the bug**
Some 16px folder icons in the "dark" variant won't receive their intended color during installation.
The icons in question are:

- `/src/16/places/folder.svg`
- `/src/16/places/folder-open.svg`
- `/src/16/places/folder-visiting.svg`

**To Reproduce**
1. execute `./install.sh grey`
2. Open `~/.local/share/icons/Tela-grey-dark/16/places/`
3. Observe that folder icons are in standard blue (#5294e2)

Note: The icons are for example used in Thunar in "List View" mode at smallest size.

**Expected behavior**
The folder icons should receive the selected color, or #aaaaaa like the other icons do
in this size class.

**Desktop (please complete the following information):**
 - OS: Debian 11 with GNOME 3.38
 - App: Thunar (and probably others)

**Additional details**
I think the icons in question are supposed to use #727272 as base color, so the install script can properly
replace the color. Instead, the have #5294e2 which the install script does NOT account for. 

A possible fix would be to add `sed -i "s/#5294e2/#aaaaaa/g" "${THEME_DIR}"/{16,22,24}/places/*.svg` to the dark variant path in install.sh. Alternatively, the files may be changed to use #727272 in the first place.

**Screenshots**
This file (among others) will not receive the proper color treatment.
![image](https://user-images.githubusercontent.com/5485569/197618792-f9057697-e69e-4ceb-9204-a6024ab5225a.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now

**Comment by nptr** [comment]
Looks good now, thanks!

**Comment by giangbang** [comment]
Hi there, I am just wondering whether this problem is fixed or not yet because I am still this. Here is my screenshot at different scale, and the icons at the side bar is just wierd.
![image](https://github.com/user-attachments/assets/c43d8191-d4b5-448a-990a-95b3a31c9bc8)
![image](https://github.com/user-attachments/assets/f981d0bb-653c-4af2-b1c7-fa5e7219eaf5)
![image](https://github.com/user-attachments/assets/30442dba-a9f6-4778-b325-f09bf0a6ac3b)

**Comment by giangbang** [comment]
I might miss it, but maybe the 22px version is just different from the rest I guess? 
In my opinion, the 16px version should be in black and white just like the 22px version, it looks nicer at the side bar and just match with other icons there, which are already black and white.
