### ISSUE TITLE
[Icon request] BTOP++

### ISSUE THREAD

**Issue by Nature1Limited** [vinceliuice/Tela-icon-theme#214]
**general information**
1. App name: BTOP++
2. App Webside: or App Github Homepage: [https://github.com/aristocratos/btop](https://github.com/aristocratos/btop)
3. App icon name: btop

**Additional context**
_review:_   [linuxhint.com](https://linuxhint.com/btop-system-monitoring-tool/)

**Comment by vinceliuice** [comment]
Added
