### ISSUE TITLE
[Icon request] Apifox

### ISSUE THREAD

**Issue by HaroldLoui** [vinceliuice/Tela-icon-theme#218]
**Tell me things about the app or icon**
1. App name: Apifox
2. App Webside: or App Github Homepage: https://www.apifox.cn/
3. App icon name: apifox
    If you don't know the app name you can open the app desktop entry file,
    and find the line: icon=[App icon name] (e.g icon=firefox),
    the word after "icon=" is the App icon name.

    But if "icon=" is followed by the specific path of an icon file, then this app will not use icon theme 
    icons.  I generally don’t create this kind of icon because this app does not use it.

**Additional context**
Add any other context or screenshots about the icon request here.
![apifox](https://user-images.githubusercontent.com/63445267/205579848-820714fc-e229-4d15-b8a6-57cfc184c492.svg)

**Comment by vinceliuice** [comment]
Fixed
