### ISSUE TITLE
Every single symbolic link is broken

### ISSUE THREAD

**Issue by Silicasandwhich** [vinceliuice/Tela-icon-theme#22]
None of the links in the links folder actually link to anywhere. It doesn't seem to affect anything, leading me to believe that the folder is deprecated. If it is, you should probably delete it, but if it isn't, you should really fix it.

**Comment by vinceliuice** [comment]
They all only works at installed folders, so they'll looks brokened at /links folder, you can check the installed themes, and then you can find they all works well, if some links still not work at installed folder, you can let me know and I'll fix!
