### ISSUE TITLE
[Icon request] Synergy

### ISSUE THREAD

**Issue by jopejoe1** [vinceliuice/Tela-icon-theme#225]
**Tell me things about the app or icon**
1. App name: Synergy
2. App Webside: https://symless.com/synergy
3. App icon name: synergy

**Additional context**
Add any other context or screenshots about the icon request here.

![Synergy logo](https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5f4f70e33f2bb63b383cce70_Synergy%20logo%20on%20white.svg)

**Comment by vinceliuice** [comment]
Added
