### ISSUE TITLE
[Icon request] Discord Development

### ISSUE THREAD

**Issue by jopejoe1** [vinceliuice/Tela-icon-theme#227]
**Tell me things about the app or icon**
1. App name: Discord Development
2. App Website: https://discord.com/
3. App icon name: discord-development

**Additional context**
Add any other context or screenshots about the icon request here.
Currently, links to the regular discord icon.
![discord](https://user-images.githubusercontent.com/34899572/216776599-335c40a0-8b43-46f7-a547-8a31da83de54.png)

**Comment by vinceliuice** [comment]
Fixed
