### ISSUE TITLE
[Icon request] NixOS Manual

### ISSUE THREAD

**Issue by jopejoe1** [vinceliuice/Tela-icon-theme#228]
**Tell me things about the app or icon**
1. App name: NixOS Manual
2. App Website: https://nixos.org/
3. App icon name: nix-snowflake

**Additional context**
Maybe also add the distributor icon for NixOS, which is the same icon.
![Nix-snowflake](https://github.com/NixOS/nixos-artwork/raw/master/logo/nix-snowflake.svg)

**Comment by vinceliuice** [comment]
Fixed
