### ISSUE TITLE
[Icon request] Prism Launcher

### ISSUE THREAD

**Issue by jopejoe1** [vinceliuice/Tela-icon-theme#229]
**Tell me things about the app or icon**
1. App name: Prism Launcher
2. App Webside: https://github.com/PrismLauncher/PrismLauncher
3. App icon name: org.prismlauncher.PrismLauncher

**Additional context**

![PrismLauncher](https://github.com/PrismLauncher/PrismLauncher/raw/develop/program_info/org.prismlauncher.PrismLauncher.Source.svg)

**Comment by vinceliuice** [comment]
Fixed
