### ISSUE TITLE
[Icon request] Android Studio (new icon)

### ISSUE THREAD

**Issue by vitorfg8** [vinceliuice/Tela-icon-theme#230]
**Tell me things about the app or icon**
1. App name: Android Studio
2. App Website: or App Github Homepage: https://developer.android.com/studio, https://flathub.org/apps/details/com.google.AndroidStudio
3. App icon name: com.google.AndroidStudio

**Additional context**
Old icon:

<img src="https://user-images.githubusercontent.com/114959996/216817509-b4c4a155-3b53-4f17-a4bc-04e3725096cc.png" width="128"> 

Theme icon:
![android-studio](https://user-images.githubusercontent.com/114959996/227062477-c09123d6-eff0-4562-bb48-b0c9c577f350.svg)

Current icon: 

![studio](https://user-images.githubusercontent.com/114959996/232225124-162828de-e0e9-4949-8c51-90344fbb464d.svg)

**Comment by vinceliuice** [comment]
Fixed
