### ISSUE TITLE
[Icon request] Fedora (new icon)

### ISSUE THREAD

**Issue by vitorfg8** [vinceliuice/Tela-icon-theme#231]
**Tell me things about the app or icon**
1. App name: Fedora
2. App Webside: or App Github Homepage: https://getfedora.org/
3. App icon name: distributor-logo-fedora

**Additional context**
Add any other context or screenshots about the icon request here.

old icon:

<img src="https://user-images.githubusercontent.com/114959996/218220874-2136d2d0-b2b8-4ef5-8b90-d4d701e3e73f.png" 
     width="128" 
     height="128" />

Theme icon:

![distributor-logo-fedora](https://user-images.githubusercontent.com/114959996/227062642-dfeec30b-d9ac-487d-b9bd-d9734d1ebc8c.svg)

new icon: 

<img src="https://user-images.githubusercontent.com/114959996/218220896-626b5063-0d34-4bd4-ada7-579c0bac5a34.png" 
     width="128" 
     height="128" />

**Comment by vinceliuice** [comment]
Fixed
