### ISSUE TITLE
 [Icon request] [Blender] (folder icon)

### ISSUE THREAD

**Issue by Beryesa** [vinceliuice/Tela-icon-theme#232]
**Tell me things about the app or icon**
1. App name: Blender
2. App Website: blender.org
3. App icon name: folder-blender

**Additional context**
Breeze has one, it would be nice!
 <img src="https://user-images.githubusercontent.com/60751519/222692070-6d79acba-bf92-4497-bd78-010ecf4e7450.png" width="300">

**Comment by vinceliuice** [comment]
Fixed
