### ISSUE TITLE
 [Icon request]: Obsidian

### ISSUE THREAD

**Issue by fewaltix** [vinceliuice/Tela-icon-theme#240]
**Tell me things about the app or icon**
1. App name: **Obsidian**
2. App Webside: or App Github Homepage: https://obsidian.md/
3. App icon name: 
`Icon=obsidian
`
Additional info:
A pretty popular open-source alternative to Notion, a markdown editor with a lot of special features and a big developer community. 
![grafik](https://user-images.githubusercontent.com/58039889/235642498-a798089b-8a04-4873-a6a0-9880bb8a163a.png)

Thank you so much for your amazing work!

**Comment by astro-ray** [comment]
Tela already has an icon for obsidian tho
