### ISSUE TITLE
[Icon request] [Thunderbird] Updating Thunderbird design

### ISSUE THREAD

**Issue by KodyVB** [vinceliuice/Tela-icon-theme#250]
**Tell me things about the app or icon**
1. App name: Thunderbird
2. App Website: [Website](https://www.thunderbird.net)
3. App icon name: thunderbird

**Additional context**
Posted below are two designs for Thunderbird's icon. The top one is the older design, which is still used by Mozilla in some areas, while the bottom one is the newer design which is being pushed out along with the v115 release. ~~One example of both being used is currently their website (provided above), where the old design is visible on the tab, while the new design is visible at the top left of the homepage.~~ The website is now using the new icon in both areas.

![Screenshot_20230722_093334](https://github.com/vinceliuice/Tela-icon-theme/assets/43708421/92711904-c943-4867-959a-975c97c88519)
Old design
![Screenshot_20230722_092556](https://github.com/vinceliuice/Tela-icon-theme/assets/43708421/68e34aa9-dcbf-4cf7-b0bf-f509266ea916)
New design

Since the new design matches Mozilla's Firefox one more, I was wondering if there were plans to update Thunderbird's icon in Tela to more closely resemble the newer design, as well.

Since Thunderbird is open source, I went to the Github page and searched for the svg file, and found [this](https://github.com/mozilla/releases-comm-central/blob/master/mail/branding/thunderbird/content/logo-gradient.svg), if that helps at all.

**Comment by LIlaUraraka** [comment]
I fully agree, the icon needs updated

**Comment by vinceliuice** [comment]
Updated
