### ISSUE TITLE
[Icon request] KDE Plasma 6 symbolic icons

### ISSUE THREAD

**Issue by jopejoe1** [vinceliuice/Tela-icon-theme#261]
**Tell me things about the app or icon**
1. App name: KDE Plasma
2. App Webside: https://community.kde.org/Plasma/Plasma_6
3. App icon name: *-symbolic (Too Many to list)

**Additional context**
KDE Plasma 6 moved all the icons that where included in the Global theme to be read from the System Icon theme and suffixed theme with -symbolic. They have added them to [Breeze](https://github.com/KDE/breeze-icons), and here is a [post](https://pointieststick.com/2023/08/12/how-all-this-icon-stuff-is-going-to-work-in-plasma-6/) from one of the devs about.

**Comment by Aely0** [comment]
With Plasma 6 being officially released for almost 2 weeks now and landing in rolling release distros, this icon theme does currently look noticeably broken due to mentioned changes. +1

**Comment by Andrew-Mattias** [comment]
+1 

It is not completely broken, but many are either breeze fallback (notifications, sound) or colored (like paste icon).

![изображение](https://github.com/vinceliuice/Tela-icon-theme/assets/91881068/b6d42c6a-cb01-429b-a657-d29290bc6cb4)

**Comment by matterhorn103** [comment]
> and here is a [post](https://pointieststick.com/2023/08/12/how-all-this-icon-stuff-is-going-to-work-in-plasma-6/) from one of the devs about.

This linked blog of Nate's is really useful what's going on.

Personally I would love it if the symbolic icons, i.e. with `-symbolic` appended, had a visual style fitting with Tela but were monochrome rather than colourful. Or, if colourful, were at least simplified significantly to aid quick identification, as the symbolic icons are often displayed very small.

**Comment by vinceliuice** [comment]
Fixed now

**Comment by zastrixarundell** [comment]
Still seems a little be inconsistent. This was on kde 5:
![image](https://github.com/vinceliuice/Tela-icon-theme/assets/30195425/fa261aed-a3b9-403b-88b9-9b9d18a7f9fc)
right now on kde 6:
![image](https://github.com/vinceliuice/Tela-icon-theme/assets/30195425/441dca1b-dec2-47fb-abe6-d29b5d0370c0)

**Comment by matterhorn103** [comment]
> Still seems a little be inconsistent. This was on kde 5: ![image](https://private-user-images.githubusercontent.com/30195425/329212357-fa261aed-a3b9-403b-88b9-9b9d18a7f9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjc3MzUsIm5iZiI6MTcxNTI2NzQzNSwicGF0aCI6Ii8zMDE5NTQyNS8zMjkyMTIzNTctZmEyNjFhZWQtYTNiOS00MDNiLTg4YjktOWI5ZDE4YTdmOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE1MTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZTIwNzY2ZjY4MTdkNzUxZWZhMDhhNGIzNjBlNzU1NDFjNmVlMGRlMmFlZTFiMmUzZDFmY2QyZjc1YTJkOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hQGuQmQJPlQpE2ZbLSDQIcWCREqWDsK1R3s0ubA-IY) right now on kde 6: ![image](https://private-user-images.githubusercontent.com/30195425/329212448-441dca1b-dec2-47fb-abe6-d29b5d0370c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjc3MzUsIm5iZiI6MTcxNTI2NzQzNSwicGF0aCI6Ii8zMDE5NTQyNS8zMjkyMTI0NDgtNDQxZGNhMWItZGVjMi00N2ZiLWFiZTYtZDI5YjVkMDM3MGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE1MTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NjAyZmViOGE1NWIxNGE4MzAyZDFmZGQwNTdhZjQ1Y2QyZjRkOTZjZDg3MDgyNDY3NzI4NDYxNTZhYTM4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTOmiULF7XFMylH7oRjQibmN92Z-GdXgZFsxA343KNo)

What is inconsistent? If it's that they don't look the same as they used to, that's because the system tray icons in Plasma 5 didn't come from Tela, they came from the Plasma style. Since in Plasma 6 they come from the icon theme (i.e. Tela), they are bound to look different now as they are different icon themes.

The issue before @vinceliuice fixed it was that many of the icons didn't have symbolic versions available, so the full-colour ones were being shown instead.

**Comment by zastrixarundell** [comment]
The icons on the plasma 5 system tray weren't default, they were changed when changing the icon theme and it seemed way more consistent than the current icons on plasma 6.

**Comment by jopejoe1** [comment]
Thanks for the work :heart:
