### ISSUE TITLE
Question about releases

### ISSUE THREAD

**Issue by beatussum** [vinceliuice/Tela-icon-theme#27]
Why don't you use the '[_GitHub release feature_](https://github.com/vinceliuice/Tela-icon-theme/releases)' (I don't think it's the right name) by using _Git tag_?
It might be easier to control the different versions.

**Comment by vinceliuice** [comment]
Release file is not necessary

**Comment by zerocon** [comment]
I was about to request the same issue. Releases are quite useful for packaging on different distros.
Maybe consider automating it https://help.github.com/en/articles/creating-releases#automatically-creating-releases

**Comment by vinceliuice** [comment]
OK! I can make releases for this theme

**Comment by beatussum** [comment]
Please, could you prefer the version naming form _yyyymmdd_ to _yyyy\_mm\_dd_: it is easier to manage the package version.

**Comment by vinceliuice** [comment]
No problem!
