### ISSUE TITLE
Question about dark theme

### ISSUE THREAD

**Issue by beatussum** [vinceliuice/Tela-icon-theme#28]
Is there a difference between the **dark theme** and the **standard one**?

**Comment by vinceliuice** [comment]
Action icons on menu are all white color at dark theme, dark icon theme is made for dark app themes

**Comment by beatussum** [comment]
Why not just link **Tela-dark/*** (except _icon-theme.cache_ and _index.theme_) to **Tela/***?

**Comment by beatussum** [comment]
Okay, excuse me, I have just understood. :smile:

**Comment by beatussum** [comment]
What I can't understand is the fact that the **dark** and **light** icons, in your theme, are the same: both are in **black** on **white**.

**Comment by vinceliuice** [comment]
Only actions and devices icon are different

**Comment by vinceliuice** [comment]
Didn't notice that you removed the code to change the color in install.sh, I have to add them back

**Comment by vinceliuice** [comment]
Now it's ok, all 16/{actions,devices,places} and 22/actions, 24/actions icons are white color at dark themes
