### ISSUE TITLE
Plasma 6 - KTorrent (symbolic icon needed)

### ISSUE THREAD

**Issue by genkieagle** [vinceliuice/Tela-icon-theme#284]
**Describe the bug**
KTorrent missing an symbolic icon on Plasma 6 tray.

**Expected behavior**
To have a symbolic icon.

**Screenshots**
![Screenshot_20240501_155847](https://github.com/vinceliuice/Tela-icon-theme/assets/160327855/b62b6267-a45f-4898-97f2-a99531eb6d9f)

**Desktop (please complete the following information):**
Operating System: openSUSE Tumbleweed 20240429
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Graphics Platform: Wayland

**Additional context**
Tela-icon-theme installed from master.
`alias tela="git clone https://github.com/vinceliuice/Tela-icon-theme.git && $HOME/Tela-icon-theme/install.sh -d $HOME/.local/share/icons -n Tela -c black"`

**Comment by vinceliuice** [comment]
You are welcome.
