### ISSUE TITLE
我下载源码 通过install.sh 手动安装了tela，请问如何手动卸载呢？

### ISSUE THREAD

**Issue by Voyiid** [vinceliuice/Tela-icon-theme#293]
**Tell me things about the app or icon**
1. App name: (e.g Firefox Browser)
2. App Webside: or App Github Homepage: (e.g www.firefox.com)
3. App icon name: (e.g firefox)
    If you don't know the app name you can open the app desktop entry file,
    and find the line: icon=[App icon name] (e.g icon=firefox),
    the word after "icon=" is the App icon name.

    But if "icon=" is followed by the specific path of an icon file, then this app will not use icon theme 
    icons.  I generally don’t create this kind of icon because this app does not use it.

**Additional context**
Add any other context or screenshots about the icon request here.

**Comment by vinceliuice** [comment]
`rm -rf $HOME/.local/share/icons/Tela*`

**Comment by Voyiid** [comment]
It works,thank you very much!
