### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by denikris** [vinceliuice/Tela-icon-theme#3]
can you add visual studio code icon on your next release of this icon, in current release it has same icon as gedit and mousepad etc, and audacious music player icon.

thank you for this great icon :-)

**Comment by vinceliuice** [comment]
Added now! you can try the new one

**Comment by denikris** [comment]
thank you for your great work, but vs code and mousepad/gedit icon still same

here screenshot side by side
![mousepad vscode](https://user-images.githubusercontent.com/16707606/53344131-8006cf00-3944-11e9-9460-ef7204711fda.png)

**Comment by vinceliuice** [comment]
Forget this, I'll make a new icon for mousepad

**Comment by denikris** [comment]
maybe make for vs code instead? i use another distro that use gedit as standard text editor(like mousepad in xubuntu), so maybe it's good to keep mousepad this way
