### ISSUE TITLE
Destination does not exist or is not a directory

### ISSUE THREAD

**Issue by xLinkOut** [vinceliuice/Tela-icon-theme#31]
Keep getting this: 
> ERROR: Destination does not exist or is not a directory.

Obviously the folder $HOME/.themes already existst, and I've tried to set permisson to 777 and owner to my user.

It worked only when I've specified another directory by -d command:
`$ ./install.sh -d ../.icons ubuntu`

**Comment by beatussum** [comment]
What is the output of `echo ${HOME}`?

**Comment by beatussum** [comment]
> Obviously the folder $HOME/.themes already existst

The default installation dir is not _${HOME}/.themes_ but _${HOME}/.local/share/icons_.

**Comment by xLinkOut** [comment]
But in the README there is:
> -d | Specify theme destination directory (Default: $HOME/.themes)
Anyway, 
`~/Tela-icon-theme$ echo ${HOME}
/home/luca
`
I'm installing as my user, not as root.

**Comment by beatussum** [comment]
So, does the directory _${HOME}/.local/share/icons_ exist?

**Comment by xLinkOut** [comment]
Nope, but why the script have to install icon's files in that directory and not in my user folder?
Btw maybe the script could create the folder if it didn't exists.

**Comment by beatussum** [comment]
The directory _$XDG_DATA_DIRS/icons_ is now preferred to _$HOME/.icons_.

**Comment by xLinkOut** [comment]
That's good to know. Thank you!

**Comment by beatussum** [comment]
I think that producing an error when user defines a non-existent directory, instead of creating it, is preferable: it avoids inadvertently creating an unwanted directory.
And the _README.md_ file is updated by #32: thank you for your report.

**Comment by vinceliuice** [comment]
I updated the install.sh to make ${HOME}/.local/share/icons when it didn't exists
