### ISSUE TITLE
[Icon Request] Peek - An animated GIF Recorder

### ISSUE THREAD

**Issue by fajaryanw** [vinceliuice/Tela-icon-theme#34]
* **App Name:** Peek
* **Description:** An animated GIF recorder
* **Webpage (optional):** https://github.com/phw/peek
* **Original Icon:**
![com uploadedlobster peek](https://user-images.githubusercontent.com/6999559/61022725-54efba00-a3d1-11e9-8507-8fc87bf5563d.png)

**Comment by vinceliuice** [comment]
No problem!
