### ISSUE TITLE
[Icon Request] JetBrains apps

### ISSUE THREAD

**Issue by mtytula** [vinceliuice/Tela-icon-theme#35]
App Names: DataGrip, Phpstorm, Webstorm, etc.
Description: Popular IDE
Webpage: https://www.jetbrains.com/

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added now!

**Comment by mtytula** [comment]
That's weird. Added icons, but icon's are not changing. I'm using DataGrip and PHPStorm (installed via snap)

**Comment by vinceliuice** [comment]
You can use gedit open the starter files and tell me the icon name, I'll add the right one

**Comment by vinceliuice** [comment]
It not use system theme icons, you have to edit the .desktop file

```
[Desktop Entry]
Version=1.0
Type=Application
Name=DataGrip
Icon=/opt/datagrip/bin/datagrip.png
Exec="/opt/datagrip/bin/datagrip.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-datagrip
```
Change `Icon=/opt/datagrip/bin/datagrip.png` to `Icon=datagrip`
