### ISSUE TITLE
Icon Request (Battery charging icon)

### ISSUE THREAD

**Issue by nopain2110** [vinceliuice/Tela-icon-theme#38]
Hi Vince,
I recognize that battery charging icon is same as normal battery icon. Please include this icon in the next release.
Thanks you!

**Comment by vinceliuice** [comment]
OK! I'll fix this

**Comment by nopain2110** [comment]
Can you change charging symbol color? Charging symbol color is same as battery color (white).
Thank you!

**Comment by vinceliuice** [comment]
Can you give me a screenshot, because I have different icons on my gnome

**Comment by nopain2110** [comment]
![charging](https://user-images.githubusercontent.com/52101938/63636392-ec1a8380-c698-11e9-89fa-8f89116c09ee.png)
![discharged](https://user-images.githubusercontent.com/52101938/63636395-f0df3780-c698-11e9-9c70-7c109482e898.png)

**Comment by vinceliuice** [comment]
Fixed now!
