### ISSUE TITLE
Missing Media Tray Icon in Manjaro KDE

### ISSUE THREAD

**Issue by crimx** [vinceliuice/Tela-icon-theme#39]
Breath/Breeze icon theme:

![image](https://user-images.githubusercontent.com/6882794/63745361-9b8f6a00-c8d4-11e9-978c-21ccc3e6b317.png)

Tela

![image](https://user-images.githubusercontent.com/6882794/63745261-54a17480-c8d4-11e9-9e1f-28c35d38674d.png)

**Comment by beatussum** [comment]
It is due to the absence of _status/media-playback-*_ icons in this theme: this icon and its dark version should be added.

**Comment by beatussum** [comment]
@vinceliuice Maybe also an option should be added in the installation script allowing the installation of a mixed theme: interesting in case you have defined a normal theme but you have a dark status bar.

**Comment by vinceliuice** [comment]
Thanks! @beatussum I'll fix this.

**Comment by beatussum** [comment]
Fixed in https://github.com/vinceliuice/Tela-icon-theme/commit/a96fe04ae1d32ce275c0ab0fde97eee576a4d6f1.

**Comment by crimx** [comment]
Confirm fixed. Thanks a lot! :heart:
