### ISSUE TITLE
wifi & battery icons shows incorrectly on gnome 3.34

### ISSUE THREAD

**Issue by hexauniverse** [vinceliuice/Tela-icon-theme#42]
![](https://i.imgur.com/djgKFqs.png)

**Comment by vinceliuice** [comment]
Download  the last version of github, I fixed this

**Comment by hexauniverse** [comment]
oh, I didn't notice. thanks

**Comment by hexauniverse** [comment]
there are still problems with wifi icon:
![](https://i.imgur.com/6guh3Ux.png)

**Comment by vinceliuice** [comment]
OK I'll check this

**Comment by vinceliuice** [comment]
I update it, you can try the last version
