### ISSUE TITLE
[EDIT] [Icon update] root device icon

### ISSUE THREAD

**Issue by beatussum** [vinceliuice/Tela-icon-theme#46]
### root device icon:

![drive-harddisk-root](https://user-images.githubusercontent.com/29466654/67162038-af010380-f360-11e9-9a65-a9bc21a53d56.png)

### other device icon:

![drive-harddisk](https://user-images.githubusercontent.com/29466654/67162076-099a5f80-f361-11e9-8330-05c6f6231942.png)

**EDIT:** sorry, I meant the fact that the _root device icon_ looks very strange with a higher resolution.

**Comment by vinceliuice** [comment]
This theme do have this icon:
![2019-10-03 07-42-52 的屏幕截图](https://user-images.githubusercontent.com/7604295/66089350-75cf4200-e5b1-11e9-9549-24e5001102cc.png)

**Comment by vinceliuice** [comment]
Does it not work?

**Comment by beatussum** [comment]
@vinceliuice ping

**Comment by beatussum** [comment]
I think that it is because of the absence of _devices/drive-harddisk-root_ in the **32** and **scalable** folders.

**Comment by vinceliuice** [comment]
OK，I'll fix this! Thanks!

**Comment by vinceliuice** [comment]
Fixed!
