### ISSUE TITLE
Tela Dark - Tray icons in Elementary os is bigger than other variants

### ISSUE THREAD

**Issue by DubininDmitry** [vinceliuice/Tela-icon-theme#5]
Tela Dark in first screen, all other icon versions in the second. Tela Dark icons in tray are bigger.
![Tela Dark](http://i.imgur.com/jklbWFv.png)
![Tela - all other icons](http://i.imgur.com/6ND8m54.png)

**Comment by vinceliuice** [comment]
Fixed now
