### ISSUE TITLE
[Icon Request] Blockdevice and Chardevice

### ISSUE THREAD

**Issue by beatussum** [vinceliuice/Tela-icon-theme#50]
**inode/blockdevice** and **inode/chardevice** appear as:
![none](https://user-images.githubusercontent.com/29466654/68605820-60e9a680-04ad-11ea-9b80-ab9e015137b4.png)

**Comment by beatussum** [comment]
I suppose that _scalable/mimetypes/inode-blockdevice.svg_ and _scalable/mimetypes/inode-chardevice.svg_ should be added.

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Fixed
