### ISSUE TITLE
[Icon request] actions/notifications-disabled and actions/notifications

### ISSUE THREAD

**Issue by beatussum** [vinceliuice/Tela-icon-theme#52]
### Breeze icons:

![notifications-disabled](https://user-images.githubusercontent.com/29466654/68902967-f7ca9300-0739-11ea-92ee-20ec25704664.png)
![notifications](https://user-images.githubusercontent.com/29466654/68902968-f8632980-0739-11ea-93a2-9b3b012eec03.png)

**Comment by vinceliuice** [comment]
I'll add this

**Comment by beatussum** [comment]
Fixed in https://github.com/vinceliuice/Tela-icon-theme/commit/a96fe04ae1d32ce275c0ab0fde97eee576a4d6f1.
