### ISSUE TITLE
[Icon Request] Simplenote

### ISSUE THREAD

**Issue by SaeedBaig** [vinceliuice/Tela-icon-theme#59]
App Name: Simplenote
Description: Note-taking app that syncs notes across platforms/devices
Webpage (optional): https://simplenote.com/
Original icon:
![Logo_of_Simplenote](https://user-images.githubusercontent.com/29703429/74297500-2ee12c80-4d9b-11ea-908a-e47c5982de65.png)

**Comment by vinceliuice** [comment]
OK!
