### ISSUE TITLE
[Icon Request] Deezer

### ISSUE THREAD

**Issue by Rogoz208** [vinceliuice/Tela-icon-theme#66]
App Name : Deezer
Description : Music streaming service
Webpage : https://www.deezer.com/
Original Icon :
  ![64995467-ff112400-d8e3-11e9-879b-e4a8e0c95dd3](https://user-images.githubusercontent.com/38566187/76092075-d71b9700-5fcf-11ea-86ea-a4de8b040bb6.png)

**Comment by vinceliuice** [comment]
Added
