### ISSUE TITLE
Missing minus and plus icon in xfce4 configs

### ISSUE THREAD

**Issue by Kyberius** [vinceliuice/Tela-icon-theme#67]
The icons for the plus and the minus of the numeric inputs are missing.
![Missing Icons](https://user-images.githubusercontent.com/12391113/76172800-a2f3d200-6199-11ea-95d8-2a9775266d14.png)

**Comment by thegreatyellow67** [comment]
Same problem in cinnamon, gnome.

**Comment by vinceliuice** [comment]
Try the last update here, I think it's fixed now

**Comment by meson11** [comment]
Seems to be fixed.

**Comment by t-zehnder** [comment]
No plus or minus in Ubuntu 20.04

**Comment by vinceliuice** [comment]
Try the last update @t-zehnder , I fixed this
