### ISSUE TITLE
KDE not using tela panel icons

### ISSUE THREAD

**Issue by redd29** [vinceliuice/Tela-icon-theme#68]
I am using Kubuntu and the panel is not using tela icons.

**Comment by vinceliuice** [comment]
Plasma status icons on panel are on plasma theme, icon theme will not change this, this is not a icon theme issue

**Comment by AndydeCleyre** [comment]
@vinceliuice That's not strictly true. I'm using the Arc Color plasma theme, and this is what my systray looks like with Tela master:

![image](https://user-images.githubusercontent.com/1787385/77701633-23ce0e80-6f8d-11ea-9c2b-0fcd4a8dff5b.png)

And this is what it looks like with latest Tela release:

![image](https://user-images.githubusercontent.com/1787385/77701818-7f000100-6f8d-11ea-9c25-d26864c3e6c8.png)

Notice the Telegram icon change.
