### ISSUE TITLE
"Other Locations" icon wrong (Gnome)

### ISSUE THREAD

**Issue by arthurflor23** [vinceliuice/Tela-icon-theme#70]
Gnome default icon (nautilus lateral menu):
![image](https://user-images.githubusercontent.com/11759042/76799474-5cf9c800-67b0-11ea-95f8-dda73098571d.png)

Tela current icon:
![image](https://user-images.githubusercontent.com/11759042/76799408-376cbe80-67b0-11ea-8ddf-d9baa3816a1b.png)

**Comment by arthurflor23** [comment]
![image](https://user-images.githubusercontent.com/11759042/76801934-60dc1900-67b5-11ea-894a-357a2dd4fa6e.png)

**Comment by vinceliuice** [comment]
I'll fix this
