### ISSUE TITLE
[Icon Request] GSConnect top menu icon

### ISSUE THREAD

**Issue by arthurflor23** [vinceliuice/Tela-icon-theme#72]
I don't know if is an icon theme problem, but another "different"  (this time in top menu) is [GSConnect](https://github.com/andyholmes/gnome-shell-extension-gsconnect) extension icon

Gnome/Adwaita:
![image](https://user-images.githubusercontent.com/11759042/76808997-29c33300-67c8-11ea-978c-e03c57e196fb.png)

Tela:
![image](https://user-images.githubusercontent.com/11759042/76809030-48c1c500-67c8-11ea-9fb1-9feb06424ba7.png)

Maybe it is the default extension (a little ugly, I think), but It was the first time that a see this icon (GS).

Anyway, I met Tela icon theme today and it's being the best icon pack to me.
Thank you very much and great job!

**Comment by vinceliuice** [comment]
Thanks! I'll update this
