### ISSUE TITLE
[Icon Request] Ankama Launcher

### ISSUE THREAD

**Issue by arthurflor23** [vinceliuice/Tela-icon-theme#73]
Hi!
This is a specific icon for Ankama Launcher (for Dofus / Wakfu games).

Ankama website: https://www.ankama.com/en/launcher
Arch package: https://aur.archlinux.org/packages/ankama-launcher/

Actually:
![image](https://user-images.githubusercontent.com/11759042/76860867-75aec000-683a-11ea-824a-bbc9a58ff55b.png)

ankama-launcher.desktop
```
[Desktop Entry]
Name=Ankama Launcher
Exec=ankama-launcher
Terminal=false
Type=Application
Icon=ankama-launcher
StartupWMClass=Ankama Launcher
X-AppImage-Version=2.11.12.6812
Comment=Ankama portal and game launcher
Categories=Game;
```

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
