### ISSUE TITLE
Feature request: Update File Icons To Reflect Type

### ISSUE THREAD

**Issue by salientos** [vinceliuice/Tela-icon-theme#75]
Would it be possible to update the filetype icons to reflect their type, for example a different colour for .sh, .py, .c, .h files etc. I appreciate this is a lot of work but would really make this lovely theme stand out from the crowd!

**Comment by vinceliuice** [comment]
No problem! I'll update this

**Comment by salientos** [comment]
> No problem! I'll update this

Thank you!

Would it be possible to be able to choose the colour of script file icons? I like them dark so that the # symbol shows clearly.  Also, do you account for when a folder is owned by root, placing a marker on the owned folder?

Keep up the great work you do!

**Comment by vallabhtiwari** [comment]
.c and .cpp files have same icon. If they were different it would be very nice
