### ISSUE TITLE
[Icon Request] Keepass Mimitype

### ISSUE THREAD

**Issue by arthurflor23** [vinceliuice/Tela-icon-theme#76]
Hi again!

mimitype: application/x-keepass2

This icon is from adwaita:
![image](https://user-images.githubusercontent.com/11759042/77182611-ce38c400-6aab-11ea-9300-750c1d47adac.png)

And Tela:
![image](https://user-images.githubusercontent.com/11759042/77182638-dc86e000-6aab-11ea-82de-c22a23017756.png)

With the white icon I just think something is missing, I don't know

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by arthurflor23** [comment]
Fixed in the new version
