### ISSUE TITLE
Theme not working on root ?

### ISSUE THREAD

**Issue by xpt1x** [vinceliuice/Tela-icon-theme#77]
![Screenshot from 2020-03-23 23-45-14](https://user-images.githubusercontent.com/33655587/77349073-7aa2d080-6d60-11ea-8abf-0fedc7724b57.png)
I have tela-blue-dark enabled still its not applying on root when i run `sudo nautilus` ?

**Comment by vinceliuice** [comment]
Did you install the theme with sudo?

**Comment by xpt1x** [comment]
Lol :laughing:  how can i be so silly
Thanks now its in user/share/icons :+1:
