### ISSUE TITLE
[KDE] Missing icon for HiFi audio devices

### ISSUE THREAD

**Issue by mvolf** [vinceliuice/Tela-icon-theme#87]
Please add an icon for HiFi audio devices (bluetooth speaker falls under this category). Now only an ugly "missing icon" icon is shown instead.

**Comment by vinceliuice** [comment]
I'll add this

**Comment by mvolf** [comment]
Great, thank you :+1:

**Comment by mvolf** [comment]
When can we expect this icon? :)

**Comment by mvolf** [comment]
@vinceliuice Did you give up on adding this icon? It's still not available/working. Ii you did, can you please suggest a workaround?

**Comment by mvolf** [comment]
This icon is now available and showing after the latest merge to master. Thanks!

**Comment by vinceliuice** [comment]
You are welcome!
