### ISSUE TITLE
Missing some icon in Gnome3.36

### ISSUE THREAD

**Issue by mrbeardad** [vinceliuice/Tela-icon-theme#88]
`DE`: Gnome3.36  
`Tela Version`: 2020-2-21
`Problem`:  
* with Tela icon
![Screenshot from 2020-05-06 20-36-33](https://user-images.githubusercontent.com/54128430/81179734-a4e0e280-8fdc-11ea-833c-fd0953813ab4.png)
* with other icon
![Screenshot from 2020-05-06 20-36-59](https://user-images.githubusercontent.com/54128430/81179759-ac07f080-8fdc-11ea-9662-22f3a4a8c262.png)
* Almost all places that need plus and minus signs cannot be displayed normally

**Comment by vinceliuice** [comment]
Download the last update here, it's fixed

**Comment by mrbeardad** [comment]
thanks~
