### ISSUE TITLE
gnote is not visible on Pocillo / Ubuntu Budgie

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/Tela-icon-theme#95]
![image](https://user-images.githubusercontent.com/996240/85798054-b456ef00-b734-11ea-873c-a467f802e6cc.png)

Thats because the (tomboy) icon is white without any border colours.

Should this icon have a border?

**Comment by vinceliuice** [comment]
Could you tell me the icon name?

**Comment by vinceliuice** [comment]
![Screenshot_20200626_095014](https://user-images.githubusercontent.com/7604295/85813899-16e0d700-b797-11ea-88f6-4f25159f5be8.png)
![Screenshot_20200626_102228](https://user-images.githubusercontent.com/7604295/85813902-19dbc780-b797-11ea-8506-d45d2ea4d57a.png)

**Comment by vinceliuice** [comment]
I installed gnote and tomboy, but I don't find this issue

**Comment by fossfreedom** [comment]
Yeah - apologies - I've reinstalled and all is well.  I'm guessing it is/was an icon-caching issue. But anyway - resolved.
