### ISSUE TITLE
[icons request] Homebank, Soundconverter, Anydesk, Element and Quodlibet

### ISSUE THREAD

**Issue by Bundy01** [vinceliuice/Tela-icon-theme#97]
Hi,

is it possible to add these icons?

Homebank:
https://launchpad.net/homebank/
![](https://launchpadlibrarian.net/8779536/homebank_64.png)

Soundconverter:
https://soundconverter.org/
![](https://soundconverter.org/logo.png)

Anydesk:
https://anydesk.com/en
![](https://helloapps.org/wp-content/uploads/2019/12/anydesk-remote-mobile-app-download.jpg)

Regards.

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
No problem! I'll update this
