### ISSUE TITLE
[icon request] Joplin

### ISSUE THREAD

**Issue by trevor-tolbert** [vinceliuice/Tela-icon-theme#98]
Can we get an icon for the Joplin note taking app?

[website](https://joplinapp.org/)

![image](https://user-images.githubusercontent.com/67977113/87341154-bda2d280-c50e-11ea-97bc-2f09e32a5a66.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
