### ISSUE TITLE
[KDE] Missing Applications Icon In System Settings

### ISSUE THREAD

**Issue by asrmarco13** [vinceliuice/Tela-icon-theme#99]
Hi,
when I use the Tela Icon Theme I don't have applications icon in System Settings -> Personalization.

![applications-icon](https://user-images.githubusercontent.com/17269293/89281411-5928ee00-d64a-11ea-8a86-adb223a80e24.png)

My System Information

![so-info](https://user-images.githubusercontent.com/17269293/89282602-11a36180-d64c-11ea-8798-5d8ded8be6fd.png)

Can you help me to fix it?

**Comment by beatussum** [comment]
It's probably because of [this change](https://github.com/KDE/systemsettings/commit/bd07ce4b7caabfaf2d7659c9807bd41e51e99a2f) from the upstream. The icon is not called _preferences-desktop-default-applications_ anymore but _applications-all_.

**Comment by beatussum** [comment]
@vinceliuice A new icon or symlink should be created.

**Comment by beatussum** [comment]
Closed by the commit https://github.com/vinceliuice/Tela-icon-theme/commit/4d1bb30c862f68e189301fc2fb324c52154218e4.
